name: alpine Runtime Scan

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            netcat-openbsd \
            ca-certificates tar

      - name: Download Alpine minirootfs
        run: |
          curl -L --retry 5 -o alpine.tar.gz \
            https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/x86_64/alpine-minirootfs-3.23.4-x86_64.tar.gz

      - name: Extract root filesystem
        run: |
          mkdir -p /mnt/alpine-root
          sudo tar -xzf alpine.tar.gz -C /mnt/alpine-root

      - name: Run Trivy scan
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

          sudo ./bin/trivy rootfs /mnt/alpine-root \
            --scanners vuln,misconfig \
            -f sarif \
            -o report.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: report.sarif
